### ISSUE TITLE
Config: add a parameter in order to not display Exception if user data on error

### ISSUE THREAD

**Issue by RomulusED69** [gordalina/GordalinaMixpanelBundle#11]
## Objective

Add a parameter in config in order to not throw an exception if user data is on error.
By default, display errors only if debug is enable.

## Why
In extra_data user, if you want to retrieve a sub property of an object but this object is null, an exception is thrown. Maybe you just want the field to be empty without errors.

## Example
```yml
gordalina_mixpanel:
    user_data_display_errors: false
    users:
        Symfony\Component\Security\Core\User\UserInterface:
            id: username
            email: email

        # All possible properties
        User:
            id: id
            first_name: first_name
            last_name: last_name
            email: email
            phone: phone
            extra_data:
                - { key: company_parent, value: company.baseCompany.companyName }
```
In this case, if baseCompany is empty, not Exception but a data ``company_parent`` null
